# Linear Algebra for CpE
## Laboratory 6 : Matrices

Now that you have a fundamental knowledge about vector representations, we'll try to look into greater dimensions.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

### Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.<br>
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using <b>shape</b>, <b>dimensions</b> and <b>size</b> attributes, we'll use them to analyze these matrices.

In [2]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [3]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [4]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [5]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [8]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their <b>shape</b> and another is according to their <b>element values</b>. We'll try to go through them.

### According to shape

#### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [10]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [11]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



#### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [4]:
mat = np.array([
    [1,1],
    [1,-1],
    [0,0]
])
## mat.shape[0] -- row size
## mat.shape[1] -- column size

## for a matrix to be square; row size = column size

2

In [12]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    

In [22]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to element values

#### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [25]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [26]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


#### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [51]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [16]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix. 

In [24]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1] -- any element along diagonal

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [6]:
d = np.diag([2,3,5,7]) ## creating diagonal out of ([elements])
#np.diag(d).shape == d.shape[0] == d.shape[1] -- square matrix
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

#### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal. 

In [36]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

#### Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [37]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

## Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$

In [38]:
theta = np.array([
              [5,3,-1],
])
describe_mat(theta)

Matrix:
[[ 5  3 -1]]

Shape:	(1, 3)
Rank:	2
Is Square: False



2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [39]:
number2_mat = np.array([
             [1,2,1],
             [0,4,-1],
             [0,0,10]
])
describe_mat(number2_mat)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown.

In [41]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$G = 
\begin{bmatrix}1&7&8\\2&2&2\\4&6&7
\end{bmatrix}$$

$$G=\left\{\begin{array} 1g_1+7g_2+8g_3 \\2g_1+2g_2+2g_3\\4g_1+6g_2+7g_3
\end{array}\right.$$

4. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [42]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H = \left\{\begin{array}
1x_1\\
2x_1+ 2y_2\\
4x_1+ 6y_2 +7z_3
\end{array}\right.
$$

$$\begin{equation*}
H = 
\begin{bmatrix}
1 & 0 & 0 \\
2 & 2 & 0 \\
4 & 6 & 7
\end{bmatrix}
\end{equation*}$$

# Matrix Algebra

### Addition

In [64]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [54]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

### Subtraction

In [49]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [59]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

### Element-wise Multiplication

In [67]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [60]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [64]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [66]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

## Activity

### Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [2]:
def mat_desc(matrix):
    
    if matrix.size > 0: 
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Shape:\t\t{matrix.shape}\nSize:\t\t{matrix.size}\nRank:\t\t{matrix.ndim}\nIs Square:\t{is_square}')                 
        if np.all(matrix == np.eye(matrix.shape[0], matrix.shape[1])): 
            identity = np.eye(matrix.shape[0], matrix.shape[1])
            print(f'\nIdentity Matrix: \n{identity}')
        elif np.all(matrix == np.ones((matrix.shape))):
            ones = np.ones((matrix.shape))
            print(f'\nOnes Matrix: \n{ones}')
        elif np.all(matrix == np.zeros((matrix.shape))):
            zero = np.zeros((matrix.shape))
            print(f'\nZero Matrix: \n{zero}')
        else: 
            print(f'\nMatrix is Scalar \n{matrix}')
    else:        
        print('Matrix is Empty')           
       

#### SAMPLE 1

In [27]:
B = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1],
   ])

In [28]:
mat_desc(B)  

Shape:		(3, 3)
Size:		9
Rank:		2
Is Square:	True

Identity Matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### SAMPLE 2

In [29]:
T = np.array([])

In [30]:
mat_desc(T)  

Matrix is Empty


#### SAMPLE 3

In [31]:
S = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])

In [32]:
mat_desc(S)  

Shape:		(3, 3)
Size:		9
Rank:		2
Is Square:	True

Zero Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### SAMPLE 4

In [3]:
L = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])

In [4]:
mat_desc(L)  

Shape:		(3, 3)
Size:		9
Rank:		2
Is Square:	True

Ones Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### SAMPLE 5

In [35]:
Y = np.array([
    [12,4,92],
    [3,9,93],
    [2,18,94],
    [9,12,94],
    [10,13,95],
    [12,30,95],
    [9,1,97]
])

In [36]:
mat_desc(Y)  

Shape:		(7, 3)
Size:		21
Rank:		2
Is Square:	False

Matrix is Scalar 
[[12  4 92]
 [ 3  9 93]
 [ 2 18 94]
 [ 9 12 94]
 [10 13 95]
 [12 30 95]
 [ 9  1 97]]


### Task 2

Create a function named `mat_operations()` that takes in two matrices or scalars an input parameters it should:<br>
 1. Display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix.
 2. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 3. Returns the sum of the matrices.
 4. Returns the differen of the matrices.
 5. Returns the element-wise multiplication of the matrices.
 6. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [49]:
def mat_operations(matrix1, matrix2):    
            
    ## DESCRIBING MATRIX 1
    if matrix1.size == 0:
            print('The First Matrix is a Null Matrix')    
    elif matrix1.shape[0] == matrix1.shape[1]:
        ## DESCRIBING MATRIX 1        
        if np.all(matrix1 == np.zeros((matrix1.shape))):
            print('The First Matrix is a Zero Matrix')
        elif np.all(matrix1 == np.ones((matrix1.shape))):
            print('The First Matrix is an Ones Matrix')
        elif np.all(matrix1 == np.eye(matrix1.shape[0], matrix1.shape[1])):
            print('The First Matrix is an Identity Matrix')
        elif np.all(matrix1 == np.diag(np.diag(matrix1))):
            print('The First Matrix is a Diagonal Matrix')
        elif np.all(matrix1 == np.triu(matrix1)):
            print('The First Matrix is an Upper Triangular Matrix')
        elif np.all(matrix1 == np.tril(matrix1)):
            print('The First Matrix is a Lower Triangular Matrix')
        else:
            print('The First Matrix is Scalar')
    elif matrix1.shape[0] != matrix1.shape[1]:
            print('The First Matrix is Scalar')
        
    ## DESCRIBING MATRIX 2
    if matrix2.size == 0:
            print('The Second Matrix is a Null Matrix')
    elif matrix2.shape[0] == matrix2.shape[1]:
        ## DESCRIBING MATRIX 2        
        if np.all(matrix2 == np.zeros((matrix2.shape))):
            print('The Second Matrix is a Zero Matrix')
        elif np.all(matrix2 == np.ones((matrix2.shape))):
            print('The Second Matrix is an Ones Matrix')
        elif np.all(matrix2 == np.eye(matrix2.shape[0], matrix2.shape[1])):
            print('The Second Matrix is an Identity Matrix')
        elif np.all(matrix2 == np.diag(np.diag(matrix2))):
            print('The Second Matrix is a Diagonal Matrix')
        elif np.all(matrix2 == np.triu(matrix2)):
            print('The Second Matrix is an Upper Triangular Matrix')
        elif np.all(matrix2 == np.tril(matrix2)):
            print('The Second Matrix is a Lower Triangular Matrix')
        else:
            print('The Second Matrix is Scalar')  
    elif matrix2.shape[0] != matrix2.shape[1]:
            print('The Second Matrix is Scalar')   

    ## CHECKING OPERATION VIABILITY
    if matrix1.size >=1 and matrix2.size >=1:  
        is_square = matrix1.shape[0] == matrix1.shape[1] and matrix2.shape[0] == matrix2.shape[1]
        if is_square == True:
            print('\nMatrix is Viable for Operation')       
            ## PERFORMING OPERATIONS
            sum_of_matrices = np.add(matrix1,matrix2)
            diff_of_matrices = np.subtract(matrix1,matrix2)
            elem_wise_mult_matrices = np.multiply(matrix1,matrix2)
            elem_wise_div_matrices = np.divide(matrix1,matrix2)
        
            print(f'\nSum of Matrices:\n{sum_of_matrices}')
            print(f'\nDifference of Matrices:\n{diff_of_matrices}')
            print(f'\nElement-Wise Multiplication of Matrices:\n{elem_wise_mult_matrices}')
            print(f'\nElement-Wise Division of Matrices:\n{elem_wise_div_matrices}')
        else:
             print('\nMatrix is Not Viable for Operation, Check Elements in Both Matrices')
    else:        
        print('\nMatrix is Not Viable for Operation, Check Elements in Both Matrices')   
    

#### SAMPLE 1

In [50]:
T = np.array([
    [6,5,7],
    [2,13,6],
    [8,9,13]
])
A = np.array([
    [5,8,6],
    [12,3,16],
    [7,6,18]
])

In [51]:
mat_operations(T, A)

The First Matrix is Scalar
The Second Matrix is Scalar

Matrix is Viable for Operation

Sum of Matrices:
[[11 13 13]
 [14 16 22]
 [15 15 31]]

Difference of Matrices:
[[  1  -3   1]
 [-10  10 -10]
 [  1   3  -5]]

Element-Wise Multiplication of Matrices:
[[ 30  40  42]
 [ 24  39  96]
 [ 56  54 234]]

Element-Wise Division of Matrices:
[[1.2        0.625      1.16666667]
 [0.16666667 4.33333333 0.375     ]
 [1.14285714 1.5        0.72222222]]


#### SAMPLE 2

In [52]:
E = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]    
])
H = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]        
])

In [53]:
mat_operations(E, H)

The First Matrix is an Ones Matrix
The Second Matrix is Scalar

Matrix is Not Viable for Operation, Check Elements in Both Matrices


#### SAMPLE 3

In [54]:
Y = np.array([
    [2,0,0],
    [0,4,0],
    [0,0,6]
    
])
U = np.array([
    [3,6,9],
    [12,15,18],
    [21,24,27]
])

In [55]:
mat_operations(Y, U)

The First Matrix is a Diagonal Matrix
The Second Matrix is Scalar

Matrix is Viable for Operation

Sum of Matrices:
[[ 5  6  9]
 [12 19 18]
 [21 24 33]]

Difference of Matrices:
[[ -1  -6  -9]
 [-12 -11 -18]
 [-21 -24 -21]]

Element-Wise Multiplication of Matrices:
[[  6   0   0]
 [  0  60   0]
 [  0   0 162]]

Element-Wise Division of Matrices:
[[0.66666667 0.         0.        ]
 [0.         0.26666667 0.        ]
 [0.         0.         0.22222222]]


#### SAMPLE 4

In [56]:
N = np.array([
    [4,8,12],
    [0,16,20],
    [0,0,24]
    
])
G = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
    
])

In [57]:
mat_operations(N, G)

The First Matrix is an Upper Triangular Matrix
The Second Matrix is Scalar

Matrix is Viable for Operation

Sum of Matrices:
[[ 9 18 27]
 [20 41 50]
 [35 40 69]]

Difference of Matrices:
[[ -1  -2  -3]
 [-20  -9 -10]
 [-35 -40 -21]]

Element-Wise Multiplication of Matrices:
[[  20   80  180]
 [   0  400  600]
 [   0    0 1080]]

Element-Wise Division of Matrices:
[[0.8        0.8        0.8       ]
 [0.         0.64       0.66666667]
 [0.         0.         0.53333333]]


#### SAMPLE 5

In [58]:
K = np.array([])
M = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])

In [59]:
mat_operations(K, M)

The First Matrix is a Null Matrix
The Second Matrix is a Zero Matrix

Matrix is Not Viable for Operation, Check Elements in Both Matrices
